version: '3'
services:
  postgresql:
    image: pg
    build:
      context: ./
      dockerfile: ./Dockerfile.postgresql
    ports:
      - 5432:5432
  python:
    image: pg-python
    build:
      context: ./
      dockerfile: ./Dockerfile.python
    depends_on:
        - postgresql
    volumes:
      - ../:/philo_alchemy
    links:
      - postgresql:pgdb
